site/Promo/Promo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('visits.urls', namespace='visits')),
    path('users/', include('users.urls', namespace='users')),
    path('', login, name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/Promo/users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout, usercompanyadd_u


app_name = 'users'

urlpatterns = [
    path('', login, name='login_p'),
    path('registration/', registration, name='registration_p'),
    path('profile/', profile, name='profile_p'),
    path('logout/', logout, name='logout_p'),
    path('companyadd/<int:company_id>/', usercompanyadd_u, name='usercompanyadd_u'),
]

site/Promo/visits/urls.py
from django.urls import path
from visits.views import visits, flats, index, houses, houses_card, companies, add_visit, edit_visit, houses_edit, \
    flats_edit, flat_contact_add, usercompanyadd, statistics_door, statistics_reaction


app_name = 'visits'

urlpatterns = [
    path('', index, name='index'),
    path('visits/', visits, name='visits_p'),
    path('visits/add_visit/', add_visit, name='add_visit_p'),
    path('visits/edit_visit/<int:visit_id>/', edit_visit, name='edit_visit_p'),
    path('flats/', flats, name='flats_p'),
    path('flats/edit_flat/<int:flat_id>/', flats_edit, name='flats_edit_p'),
    path('flats/flat_contact/edit/<int:flat_id>/', flat_contact_add, name='flat_contact_add'),
    path('houses/', houses, name='houses_p'),
    path('visits/edit_house/<int:house_id>/', houses_edit, name='edit_house_p'),
    path('houses_card/', houses_card, name='houses_card_p'),
    path('companies/', companies, name='companies_p'),
    path('company/add/<int:company_id>/', usercompanyadd, name='usercompanyadd'),
    path('visits/statistics_door/', statistics_door, name='statistics_door'),
    path('visits/statistics_reaction/', statistics_reaction, name='statistics_reaction'),
]

site/Promo/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    phone = models.IntegerField(default=0)

site/Promo/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control validate col-xl-9 col-lg-8 col-md-8 col-sm-7',
        'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Придумайте логин'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Придумайте пароль', }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Придумайте пароль', }))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Имя пользователя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Фамилия пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control validate', 'placeholder': 'email пользователя '}))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control validate', 'placeholder': 'Телефон пользователя', 'type': 'number'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'username', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control validate'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control validate'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control validate', 'readonly': True}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control validate', 'type': 'number'}))
   # image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'btn'}), required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control validate', 'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'username')

site/Promo/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User
from visits.models import Flat, House, Visit, Company, UserCompanies, CompaniesHouse
from visits.forms import UserCompaniesForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('visits:index'))
    else:
        form = UserLoginForm()
    context = {
        'form': form,
        'title': 'Вход в систему',
        'title_box': 'Введите ваш логин/пароль',
        'report_box': 'Неверный логин/пароль',
        'label_login': 'Логин',
        'label_pass': 'Пароль',
        'button_enter': 'Вход',
        'bottom_register': 'Регистрация',
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Вы успешно зарегистрированы!')
            return HttpResponseRedirect(reverse('users:login_p'))
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
        'title': 'Регистрация нового пользователя',
        'table_title': 'Создание учетной записи',
        'table_first_name': 'Имя',
        'table_last_name': 'Фамилия',
        'table_email': 'Электронная почта',
        'table_phone': 'Номер телефона',
        'table_login': 'Логин',
        'table_pass': 'Пароль',
        'table_pass_confirm': 'Подтверждение пароля',
        'button_accept': 'Сохранить',
        'button_cancel': 'Отмена',
        'photo': 'Фотография',
        'button_photo': 'Выбрать',
        'top_menu_is_director': True,
    }
    return render(request, 'users/register.html', context)


def profile(request):
    user = request.user
    companies = Company.objects.all()
    vuserid = User.objects.get(username=user).id
    usrcomp = UserCompanies.objects.filter(UserCompanies_User=user)
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile_p'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        'vformuserid': vuserid,
        'form': form,
        'title': 'Страница учетной записи пользователя',
        'table_title': 'Просмотр учетной записи',
        'table_first_name': 'Имя',
        'table_last_name': 'Фамилия',
        'table_email': 'Электронная почта',
        'table_phone': 'Номер телефона',
        'table_login': 'Логин',
        'table_pass': '',
        'table_pass_confirm': '',
        'button_accept': 'Сохранить',
        'button_cancel': 'Отмена',
        'button_add': 'Добавить',
        'photo': 'Фотография',
        'button_photo': 'Выбрать',
        'top_menu_username': user,
        'top_menu_dashboard': 'Главная страница',
        'top_menu_reports': 'Отчеты',
        'top_menu_visits': 'ОБХОДЫ',
        'top_menu_accounts': 'Учетная запись',
        'top_menu_logout': 'Выйти',
        'top_menu_directories': 'Справочники',
        'top_menu_is_director': True,
        'table_column_top_name_1': 'Наименование',
        'table_column_top_name_2': 'Адрес',
        'table_column_top_name_3': 'Директор',
        'table_column_top_name_4': 'ИНН',
        'houses_list': House.objects.all(),
        'companies': companies,
        'usercompanies_list': usrcomp
    }
    return render(request, 'users/profile.html', context)


def usercompanyadd_u(request, company_id):
    companies = Company.objects.all()
    company = Company.objects.get(id=company_id)
    usercompanies = UserCompanies.objects.filter(UserCompanies_User=request.user, UserCompanies_Company=company)
    if not usercompanies.exists():
        UserCompanies.objects.create(UserCompanies_User=request.user, UserCompanies_Company=company)
    else:
        messages.error(request, 'Сотрудник уже привязан к данной компании')
    context = {
        'companies': companies,
    }
    return HttpResponseRedirect(request.META['HTTP_REFERER'], context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:login_p'))

site/Promo/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

site/Promo/users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">
</head>

<body class="bg03">
    <div class="container">
        <div class="row tm-mt-big">
            <div class="col-12 mx-auto tm-login-col">

                {% if messages or form.non_field_errors %}
                    <div class="alert
                            {% if messages %} alert-success {% else %} alert-warning {% endif %}
                             d-flex align-items-center" role="alert">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                        <div>
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                <div class="bg-white tm-block">
                    <div class="row">
                        <div class="col-12 text-center">
                            <i class="fas fa-3x fa-tachometer-alt tm-site-icon text-center"></i>
                            <h2 class="tm-block-title mt-3">{{ title_box }}</h2>
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-12">
                            <form action="{% url 'users:login_p' %}" method="post" class="tm-login-form">
                                {% csrf_token %}

                               <div class="input-group">
                                 <label for="username" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">{{ label_login }}</label>
                                 {{ form.username }}
                               </div>
                               <div class="input-group mt-3">
                                 <label for="password" class="col-xl-4 col-lg-4 col-md-4 col-sm-5 col-form-label">{{ label_pass }}</label>
                                 {{ form.password }}
                               </div>
                               <div class="input-group mt-3">
                                    <button type="submit" class="btn btn-primary d-inline-block mx-auto">{{ button_enter }}</button>
                                </div>
                                <div class="input-group mt-3 d-inline-block text-center">
                                    <em><a href="{% url 'users:registration_p' %}">{{ bottom_register }}</a></em>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="row tm-mt-big">
        </footer>
    </div>
</body>

</html>

site/Promo/users/templates/users/profile.html
{% extends 'visits/base.html'%}
{% load static %}


{% block class %}
<body class="bg03">
{% endblock %}
{% block content %}
        <div class="row  tm-mt-big">
            <div class="tm-col tm-col-big">
                <div class="bg-white tm-block">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="tm-block-title">{{ table_title }}</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <form action="{% url 'users:profile_p' %}" class="tm-signup-form" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="login">{{ table_login }}</label>
                                    {{ form.username }}
                                </div>
                                <div class="form-row">
                                <div class="form-group">
                                    <label for="password1">{{ table_pass }}</label>
                                    {{ form.password1 }}
                                </div>
                                <div class="form-group">
                                    <label for="password2">{{ table_pass_confirm }}</label>
                                    {{ form.password2 }}
                                </div>

                                <div class="form-row">
                                <div class="form-group mr-4">
                                    <label for="name">{{ table_first_name }}</label>
                                    {{ form.first_name }}
                                </div>
                                 <div class="form-group">
                                    <label for="surname">{{ table_last_name }}</label>
                                    {{ form.last_name }}
                                </div>
                                <div class="form-group mr-4">
                                    <label for="email">{{ table_email }}</label>
                                    {{ form.email }}
                                </div>

                                <div class="form-group">
                                    <label for="phone">{{ table_phone }}</label>
                                    {{ form.phone }}
                                </div>
                                </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group">

                                        <button type="submit" class="btn btn-primary btn-lg mr-4">{{ button_accept }}
                                        </button>

                                    </div>
                                    <div class="form-group">

                                        <a class="btn btn-primary btn-lg" href="{% url 'visits:index' %}" role="button">{{ button_cancel }}</a>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
  <div class="col-xl-7 col-lg-10 tm-md-10 tm-sm-10 tm-col">
                <div class="bg-white tm-block">
                    <h2 class="tm-block-title d-inline-block">Компании пользователя <a>{{ vformuserid }}</a></h2>
                    <div>

                         <p>

                        </p>

                    </div>
                        <div class="table-responsive">
                            <table class="table table-hover table-striped tm-table-striped-even mt-3" id="companiesWEB">
                                <thead>
                                    <tr class="tm-bg-gray">
                                        <th scope="col">{{ table_column_top_name_1 }}</th>
                                        <th scope="col" class="text-center">{{ table_column_top_name_2 }}</th>
                                        <th scope="col" class="text-center">{{ table_column_top_name_3 }}</th>
                                        <th scope="col">{{ table_column_top_name_4 }}</th>
                                        <th scope="col"></th>
                                    </tr>
                                </thead>
                        <tbody>

                                    {% for company in companies %}
                                        {% for usercomp in usercompanies_list %}
                                    <tr>
                                            {% if company.id == usercomp.UserCompanies_Company_id %}
                                                <td class="tm-product-name">{{ company.Company_Name }}</td>
                                                <td class="text-center">{{ company.Company_Place }} {{ company.Company_Street }} {{ company.Company_House_Number }}</td>
                                                <td class="text-center">{{ company.Company_Director }}</td>
                                                <td class="text-center">{{ company.Company_INN }}</td>
                                            {% endif %}
                                    </tr>
                                    {% endfor %}
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                </div>
            </div>
        </div>
        </div>
{% endblock %}
{% block end_html %}
    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- https://jquery.com/download/ -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- https://getbootstrap.com/ -->
</body>
</html>
{% endblock %}

site/Promo/users/templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">
</head>

<body class="bg03">
    <div class="container">

        <!-- row -->
        <div class="row tm-content-row tm-mt-big">
            <div class="tm-col tm-col-small">
            </div>
            <div class="tm-col tm-col-big">
                <div class="bg-white tm-block">
                    <div class="row">
                        <div class="col-12">
                            <h2 class="tm-block-title">{{ table_title }}</h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <form action="" class="tm-signup-form">
                                <div class="form-group">
                                    <label for="name">{{ table_first_name }}</label>
                                    <input placeholder="" id="name" name="name" type="text" class="form-control validate">
                                </div>
                                 <div class="form-group">
                                    <label for="surname">{{ table_last_name }}</label>
                                    <input placeholder="" id="surname" name="surname" type="text" class="form-control validate">
                                </div>
                                <div class="form-group">
                                    <label for="email">{{ table_email }}</label>
                                    <input placeholder="" id="email" name="email" type="email" class="form-control validate">
                                </div>
                                <div class="form-group">
                                    <label for="phone">{{ table_phone }}</label>
                                    <input placeholder="" id="phone" name="phone" type="tel" class="form-control validate">
                                </div>
                                <div class="form-group">
                                    <label for="login">{{ table_login }}</label>
                                    <input placeholder="" id="login" name="login" type="text" class="form-control validate">
                                </div>
                                <div class="form-group">
                                    <label for="password">{{ table_pass }}</label>
                                    <input placeholder="******" id="password" name="password" type="password" class="form-control validate">
                                </div>
                                <div class="form-group">
                                    <label for="password2">{{ table_pass_confirm }}</label>
                                    <input placeholder="******" id="password2" name="password2" type="password" class="form-control validate">
                                </div>
                                <div class="row">
                                    <div class="col-14 col-sm-4">
                                        <button type="submit" class="btn btn-primary btn-lg">{{ button_accept }}
                                        </button>
                                    </div>
                                    <div class="col-12 col-sm-8">
                                        <a class="btn btn-primary btn-lg" href="{% url 'users:login_p' %}" role="button">{{ button_cancel }}</a>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tm-col tm-col-big">
                <div class="bg-white tm-block">
                    <h2 class="tm-block-title">{{ photo }}</h2>
                    <img src="img/profile-image.png" alt="Profile Image" class="img-fluid">
                    <div class="custom-file mt-3 mb-3">
                        <input id="fileInput" type="file" style="display:none;" />
                        <input type="button" class="btn btn-primary d-block mx-xl-auto" value="{{ button_photo }}" onclick="document.getElementById('fileInput').click();"
                        />
                    </div>
                </div>
            </div>
        </div>
        <footer class="row tm-mt-small">
        </footer>
    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <!-- https://jquery.com/download/ -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- https://getbootstrap.com/ -->
</body>

</html>