site/Promo/Promo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from users.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('visits.urls', namespace='visits')),
    path('users/', include('users.urls', namespace='users')),
    path('', login, name='login'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/Promo/users/urls.py
from django.urls import path
from users.views import login, registration, profile, logout, usercompanyadd_u


app_name = 'users'

urlpatterns = [
    path('', login, name='login_p'),
    path('registration/', registration, name='registration_p'),
    path('profile/', profile, name='profile_p'),
    path('logout/', logout, name='logout_p'),
    path('companyadd/<int:company_id>/', usercompanyadd_u, name='usercompanyadd_u'),
]

site/Promo/visits/urls.py
from django.urls import path
from visits.views import visits, flats, index, houses, houses_card, companies, add_visit, edit_visit, houses_edit, \
    flats_edit, flat_contact_add, usercompanyadd, statistics_door, statistics_reaction


app_name = 'visits'

urlpatterns = [
    path('', index, name='index'),
    path('visits/', visits, name='visits_p'),
    path('visits/add_visit/', add_visit, name='add_visit_p'),
    path('visits/edit_visit/<int:visit_id>/', edit_visit, name='edit_visit_p'),
    path('flats/', flats, name='flats_p'),
    path('flats/edit_flat/<int:flat_id>/', flats_edit, name='flats_edit_p'),
    path('flats/flat_contact/edit/<int:flat_id>/', flat_contact_add, name='flat_contact_add'),
    path('houses/', houses, name='houses_p'),
    path('visits/edit_house/<int:house_id>/', houses_edit, name='edit_house_p'),
    path('houses_card/', houses_card, name='houses_card_p'),
    path('companies/', companies, name='companies_p'),
    path('company/add/<int:company_id>/', usercompanyadd, name='usercompanyadd'),
    path('visits/statistics_door/', statistics_door, name='statistics_door'),
    path('visits/statistics_reaction/', statistics_reaction, name='statistics_reaction'),
]

site/Promo/visits/models.py
from django.db import models
from users.models import User


class House(models.Model):
    House_Place = models.CharField(max_length=32)
    House_Street = models.CharField(max_length=150)
    House_Number = models.CharField(max_length=32)
    House_Floor_Numbers = models.IntegerField(3, default=0)
    House_Amount_Entrances = models.IntegerField(3)
    House_Amount_Flats = models.IntegerField(5, default=0)

    def __str__(self):
        return f'{self.House_Place}, {self.House_Street}, {self.House_Number}'


class Flat(models.Model):
    Flat_House_Address = models.TextField(null=True, blank=True)
    Flat_Number = models.IntegerField(5, default=0)
    Flat_Owner = models.CharField(max_length=150)
    House = models.ForeignKey(to=House, on_delete=models.CASCADE)

    def __str__(self):
        return f'Квартира: {self.Flat_Number} | Дом: {self.Flat_House_Address} | Владелец: {self.Flat_Owner}'


class FlatContact(models.Model):
    FlatContact_Name = models.CharField(max_length=150)
    FlatContact_Phone = models.IntegerField(32, default=0)
    FlatContact_Comment = models.TextField(null=True, blank=True)
    Flat = models.ForeignKey(to=Flat, on_delete=models.CASCADE)


class Visit(models.Model):
    Visit_Num = models.IntegerField(32, default=0)
    Visit_Date = models.DateField(null=True, blank=True)
    Visit_Time = models.TimeField(null=True, blank=True)
    Visit_Company = models.CharField(max_length=150)
    Visit_Employee = models.CharField(max_length=150)
    Visit_House = models.TextField(null=True, blank=True)
    Visit_Door = models.BooleanField(null=True, blank=True)
    Visit_Reaction = models.CharField(max_length=25)
    User = models.ForeignKey(to=User, on_delete=models.PROTECT)

    def __str__(self):
        return f'Обход №: {self.Visit_Num} | Дом: {self.Visit_House} | Сотрудник: {self.Visit_Employee} ' \
               f'| Компания: {self.Visit_Company}'


class VisitFlat(models.Model):
    VisitFlat_Visit = models.ForeignKey(to=Visit, on_delete=models.CASCADE)
    VisitFlat_Flat = models.IntegerField(5, default=0)


class Company(models.Model):
    Company_Name = models.CharField(max_length=150)
    Company_INN = models.IntegerField(25, default=0)
    Company_Director = models.CharField(max_length=150)
    Company_Place = models.CharField(max_length=32)
    Company_Street = models.CharField(max_length=150)
    Company_House_Number = models.CharField(max_length=32)

    def __str__(self):
        return f'{self.Company_Name}'

#    def __str__(self):
#        return f'Компания: {self.Company_Name} | Директор: {self.Company_Director}'


class UserCompanies(models.Model):
    UserCompanies_User = models.ForeignKey(to=User, on_delete=models.CASCADE)
    UserCompanies_Company = models.ForeignKey(to=Company, on_delete=models.CASCADE)


class CompaniesHouse(models.Model):
    CompaniesHouse_Company = models.ForeignKey(to=Company, on_delete=models.CASCADE)
    CompaniesHouse_House = models.ForeignKey(to=House, on_delete=models.CASCADE)

site/Promo/visits/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import messages
from django.urls import reverse
from django.db.models import Count, Case, When, IntegerField, F
from visits.models import Flat, FlatContact, House, Visit, Company, UserCompanies, CompaniesHouse, VisitFlat
from users.models import User
from visits.forms import FlatsAddForm, FlatsEditForm, FlatsContactEditForm, CompaniesEditForm, VisitsAddForm, \
    VisitsFlatsAddForm, \
    VisitsEditForm, VisitsFlatsEditForm, HousesAddForm, HousesEditForm, UserCompaniesForm, StatDoorForm, StatReactForm


def index(request):
    user = request.user
    context = {
        'title': 'Сайт для ведения промо - компаний',
        'top_menu_username': user,
        'top_menu_dashboard': 'Главная страница',
        'top_menu_reports': 'Отчеты',
        'top_menu_visits': 'ОБХОДЫ',
        'top_menu_accounts': 'Учетная запись',
        'top_menu_logout': 'Выйти',
        'top_menu_directories': 'Справочники',
        'top_menu_reports_door': 'Статистика по дверям',
        'top_menu_reports_reaction': 'Статистика по реакциям',
        'top_menu_reports_contacts': 'Статистика по контактам',
        'top_menu_is_director': True,

    }
    return render(request, 'visits/Index.html', context)


def flats(request):
    if request.method == 'POST':
        form = FlatsAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Новая квартира добавлена!')
            return HttpResponseRedirect(reverse('visits:flats_p'))
    else:
        form = FlatsAddForm()
    user = request.user
    context = {
        'form': form,
        'title': 'Справочник квартир',
        'top_menu_username': user,
        'top_menu_dashboard': 'Главная страница',
        'top_menu_reports': 'Отчеты',
        'top_menu_reports_door': 'Статистика по дверям',
        'top_menu_reports_reaction': 'Статистика по реакциям',
        'top_menu_reports_contacts': 'Статистика по контактам',
        'top_menu_visits': 'ОБХОДЫ',
        'top_menu_accounts': 'Учетные записи',
        'top_menu_logout': 'Выйти',
        'top_menu_directories': 'Справочники',
        'top_menu_is_director': True,
        'top_menu_flats': 'Справочник квартир',
        'table_column_top_name_1': 'Номер квартиры',
        'table_column_top_name_2': 'Дом',
        'table_column_top_name_3': 'Владелец',
        'table_column_top_name_4': '',
        'table_right_top_button': 'Добавить квартиру',
        'table_left_but_button': 'Удалить выбранные квартиры',
        'column_right_top_name': 'Список домов',
        'column_right_bot_button': 'Добавить дом',
        'Page_list': 'Страница',
        'flats_list': Flat.objects.order_by('Flat_House_Address'),
        'houses_list': House.objects.all()

    }
    return render(request, 'visits/flats_page.html', context)


def flats_edit(request, flat_id):
    user = request.user
    eflatid = Flat.objects.get(id=flat_id)
    if request.method == 'POST':
        flat_form = FlatsEditForm(request.POST, instance=eflatid)
        flatcontact_form = FlatsContactEditForm(request.POST)
        if flat_form.is_valid() and flatcontact_form.is_valid():
            flat = flat_form.save()
            flatcontact = flatcontact_form.save(commit=False)
            flatcontact.Flat = flat
            flatcontact.save()
            messages.success(request, 'Данные по квартире изменены!')
            # return redirect('edit_flats.html')   Перенаправление на страницу успешного сохранения
            # return HttpResponseRedirect(reverse('visits:flats_edit_p'))
    else:
        flat_form = FlatsEditForm(instance=eflatid)
        flatcontact_form = FlatsContactEditForm()
    eflatcontact = FlatContact.objects.filter(Flat_id=flat_id)
    context = {
        'flat': eflatid,
        'form': flat_form,
        'contact_form': flatcontact_form,
        'title': 'Справочник квартир',
        'top_menu_username': user,
        'top_menu_dashboard': 'Главная страница',
        'top_menu_reports': 'Отчеты',
        'top_menu_visits': 'ОБХОДЫ',
        'top_menu_reports_door': 'Статистика по дверям',
        'top_menu_reports_reaction': 'Статистика по реакциям',
        'top_menu_reports_contacts': 'Статистика по контактам',
        'top_menu_accounts': 'Учетные записи',
        'top_menu_logout': 'Выйти',
        'top_menu_directories': 'Справочники',
        'top_menu_is_director': True,
        'top_menu_flats': 'Справочник квартир',
        'table_column_top_name_1': 'Номер квартиры',
        'table_column_top_name_2': 'Дом',
        'table_column_top_name_3': 'Владелец',
        'contact_table_column_top_name_1': 'Имя',
        'contact_table_column_top_name_2': 'Телефон',
        'contact_table_column_top_name_3': 'Комментарий',
        'flat_contact_empty': 'Контактная информация не заполнена!',
        'FlatContact_Name_lbl': 'Имя',
        'FlatContact_Phone_lbl': 'Телефон',
        'FlatContact_Comment_lbl': 'Комментарий',
        'table_right_top_button': 'Добавить квартиру',
        'table_left_but_button': 'Удалить выбранные квартиры',
        'column_right_top_name': 'Контактная информация',
        'column_right_bot_button': '',
        'Page_list': 'Страница',
        'flats_list': Flat.objects.order_by('Flat_House_Address'),
        'flatscontact_list': eflatcontact

    }
    return render(request, 'visits/flats_edit_page.html', context)


def flat_contact_add(request, flat_id):
    vflatid = Flat.objects.get(id=flat_id)
    contform = FlatsContactEditForm(request.POST)
    if contform.is_valid():
        vflatcontact = contform.save(commit=False)
        vflatcontact.Flat = vflatid
        vflatcontact.save()
    eflatcontact = FlatContact.objects.filter(Flat_id=flat_id)
    context = {
        'flat': vflatid,
        'form_contact': contform,
        'flatscontact_list': eflatcontact,
        'contact_table_column_top_name_1': 'Имя',
        'contact_table_column_top_name_2': 'Телефон',
        'contact_table_column_top_name_3': 'Комментарий',
    }
    return HttpResponseRedirect(request.META['HTTP_REFERER'], context)


def houses(request):
    user = request.user
    if request.method == 'POST':
        form = HousesAddForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Новый дом добавлен!')
            return HttpResponseRedirect(reverse('visits:houses_p'))
    else:
        form = HousesAddForm()
        # companieshouse = CompaniesHouse.objects.filter(UserCompanies_User=user)
    context = {
        'form': form,
        'title': 'Справочник домов',
        'top_menu_username': user,
        'top_menu_dashboard': 'Главная страница',
        'top_menu_reports': 'Отчеты',
        'top_menu_reports_door': 'Статистика по дверям',
        'top_menu_reports_reaction': 'Статистика по реакциям',
        'top_menu_reports_contacts': 'Статистика по контактам',
        'top_menu_visits': 'ОБХОДЫ',
        'top_menu_accounts': 'Учетные записи',
        'top_menu_logout': 'Выйти',
        'top_menu_directories': 'Справочники',
        'top_menu_is_director': True,
        'top_menu_flats': 'Справочник домов',
        'table_column_top_name_1': 'Адрес',
        'table_column_top_name_2': 'Номер дома',
        'table_column_top_name_3': 'Этажность',
        'table_column_top_name_4': 'Количество подъездов',
        'table_column_top_name_5': 'Количество квартир',
        'table_right_top_button': 'Добавить дом Копка',
        'table_left_but_button': 'Удалить выбранный дом',
        'column_right_top_name': 'Список квартир',
        'column_right_bot_button': 'Добавить новую квартиру',
        'Page_list': 'Страница',
        'houses_list': House.objects.all(),
        'flats_list': Flat.objects.all(),
        'houses_table_list': ['Дом_1', 'Дом_2', 'Дом_3', 'Дом_4', 'Дом_5', 'Дом_6', 'Дом_7', 'Дом_8', 'Дом_9']

    }
    return render(request, 'visits/houses_page.html', context)


def houses_edit(request, house_id):
    user = request.user
    ehouseid = House.objects.get(id=house_id)
    if request.method == 'POST':
        house_form = HousesEditForm(request.POST, instance=ehouseid)
        if house_form.is_valid():
            house_form.save()
            messages.success(request, 'Дом изменен!')
    else:
        house_form = HousesEditForm(instance=ehouseid)
    context = {
        'form': house_form,
        'title': 'Справочник домов',
        'top_menu_username': user,
        'top_menu_dashboard': 'Главная страница',
        'top_menu_reports': 'Отчеты',
        'top_menu_reports_door': 'Статистика по дверям',
        'top_menu_reports_reaction': 'Статистика по реакциям',
        'top_menu_reports_contacts': 'Статистика по контактам',
        'top_menu_visits': 'ОБХОДЫ',
        'top_menu_accounts': 'Учетные записи',
        'top_menu_logout': 'Выйти',
        'top_menu_directories': 'Справочники',
        'top_menu_is_director': True,
        'top_menu_flats': 'Справочник домов',
        'table_column_top_name_1': 'Адрес',
        'table_column_top_name_2': 'Номер дома',
        'table_column_top_name_3': 'Этажность',
        'table_column_top_name_4': 'Количество подъездов',
        'table_column_top_name_5': 'Количество квартир',
        'table_right_top_button': 'Добавить дом Копка',
        'table_left_but_button': 'Удалить выбранный дом',
        'column_right_top_name': 'Список квартир',
        'column_right_bot_button': 'Добавить новую квартиру',
        'Page_list': 'Страница',
        'flathouseid': ehouseid,
        'houses_list': House.objects.all(),
        'flats_list': Flat.objects.all(),
        'houses_table_list': ['Дом_1', 'Дом_2', 'Дом_3', 'Дом_4', 'Дом_5', 'Дом_6', 'Дом_7', 'Дом_8', 'Дом_9']


site/Promo/visits/templates/visits/adddel_company_to_user.html
<form method="post" action="{% url 'visits:usercompanyadd_p' %}">
    {% csrf_token %}
    {% if company.id == usercomp.id %}
        <td><input type="text" name="company_id" value="{{ company.id }}">
            <button type="submit" class="btn btn-warning btn-sm">-</button></td>
    {% else %}
        <td><input type="text" name="company_id" value="{{ company.id }}">
            <button type="submit" class="btn btn-success btn-sm">+</button></td>
    {% endif %}
</form>

site/Promo/visits/templates/visits/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <!-- https://fonts.google.com/specimen/Open+Sans -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <!-- https://fontawesome.com/ -->

{% block calendar %} {% endblock %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="{% static 'css/tooplate.css'%}">
</head>
<!-- Navigation -->
{% block class %} {% endblock %}
    <div class="" id="home">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-xl navbar-light bg-light">
                        <a class="navbar-brand" href="{% url 'visits:index' %}">
                            <i class="fas fa-3x fa-tachometer-alt tm-site-icon"></i>
                            <h1 class="tm-site-title mb-0">{{ top_menu_username }}</h1>
                        </a>
                        <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav mx-auto">
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'visits:index' %}">{{ top_menu_dashboard }}
                                        <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        {{ top_menu_reports }}
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'visits:statistics_door' %}">{{ top_menu_reports_door }}</a>
                                        <a class="dropdown-item" href="{% url 'visits:statistics_reaction' %}">{{ top_menu_reports_reaction }}</a>
                                        <a class="dropdown-item" href="#">{{ top_menu_reports_contacts }}</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'visits:visits_p' %}">{{ top_menu_visits }}</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'users:profile_p' %}">{{ top_menu_accounts }}</a>
                                </li>
                                {% if top_menu_is_director %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        {{ top_menu_directories }}
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{% url 'visits:companies_p' %}">Компании</a>
                                        <a class="dropdown-item" href="{% url 'visits:houses_p' %}">Дома</a>
                                        <a class="dropdown-item" href="{% url 'visits:flats_p' %}">Квартиры</a>
                                    </div>
                                </li>
                                {% endif %}
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link d-flex" href="{% url 'users:logout_p' %}">
                                        <i class="far fa-user mr-2 tm-logout-icon"></i>
                                        <span>{{ top_menu_logout }}</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
            <!-- row -->
{% block content %} {% endblock %}
            <footer class="row tm-mt-small">
            </footer>
{% block end_html %} {% endblock %}

site/Promo/visits/templates/visits/companies_page.html
{% extends 'visits/base.html'%}
{% load static %}

{% block class %}
<body id="reportsPage" class="bg02">
{% endblock %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% block content %}
            <div class="row tm-content-row tm-mt-big">
                <div class="col-xl-9 col-lg-12 tm-md-12 tm-sm-12 tm-col">
                    <div class="bg-white tm-block h-100">
                        <div class="row">
                            <div class="col-md-8 col-sm-12">
                                <h2 class="tm-block-title d-inline-block">{{ top_menu_flats }}</h2>

                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover table-striped tm-table-striped-even mt-3" id="companiesWEB">
                                <thead>
                                    <tr class="tm-bg-gray">
                                        <th scope="col"></th>
                                        <th scope="col">{{ table_column_top_name_1 }}</th>
                                        <th scope="col" class="text-center">{{ table_column_top_name_2 }}</th>
                                        <th scope="col" class="text-center">{{ table_column_top_name_3 }}</th>
                                        <th scope="col">{{ table_column_top_name_4 }}</th>
                                        <th scope="col"></th>
                                    </tr>
                                </thead>
                                <thead>
                                    <form method="post" action="{% url 'visits:companies_p' %}">
                                        {% csrf_token %}
                                    <tr class="tm-bg-gray">
                                        <th scope="col"></th>
                                        <td>{{ form.Company_Name }}</td>
                                        <td>{{ form.Company_Place }} {{ form.Company_Street }} {{ form.Company_House_Number }}</td>
                                        <td>{{ form.Company_Director }}</td>
                                        <td>{{ form.Company_INN }}</td>
                                        <td><button type="submit" class="btn btn-success btn-sm">Добавить компанию</button></td>

                                    </tr>
                                    </form>
                                </thead>
                                <tbody>
                                    {% for company in companies_list %}

                                            <tr>
                                                <th scope="row">
                                                <input type="checkbox" aria-label="Checkbox" name="company">
                                                </th>
                                                <td class="tm-product-name">{{ company.Company_Name }}</td>
                                                <td class="text-center">{{ company.Company_Place }} {{ company.Company_Street }} {{ company.Company_House_Number }}</td>
                                                <td class="text-center">{{ company.Company_Director }}</td>
                                                <td class="text-center">{{ company.Company_INN }}</td>
                                                <td><a type="submit" class="btn btn-success btn-sm" href="{% url 'visits:usercompanyadd' company.id %}">+</a>
                                                    <a type="submit" class="btn btn-warning btn-sm" href="{% url 'visits:usercompanyadd' company.id %}">-</a>
                                                </td>


                                        </tr>

                                    {% endfor %}


                                </tbody>
                            </table>
                        </div>



                        <div class="tm-table-mt tm-table-actions-row">
                            <div class="tm-table-actions-col-left">
                                <button class="btn btn-danger">{{ table_left_but_button }}</button>
                            </div>
                            <div class="tm-table-actions-col-right">
                                <span class="tm-pagination-label">{{ Page_list }}</span>
                                <nav aria-label="Page navigation" class="d-inline-block">
                                    <ul class="pagination tm-pagination">
                                        <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                                        <li class="page-item">
                                            <span class="tm-dots d-block">...</span>
                                        </li>
                                        <li class="page-item"><a class="page-link" href="#">13</a></li>
                                        <li class="page-item"><a class="page-link" href="#">14</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-xl-3 col-lg-12 tm-md-12 tm-sm-12 tm-col">
                    <div class="bg-white tm-block h-30">
                        <h2 class="tm-block-title d-inline-block">{{ column_left_top_name }}</h2>
                        <table class="table table-hover table-striped mt-2" id="usersWEB">
                            <tbody>
                                {% for usercompanie in usercompanies_list %}
                                <tr>
                                    <td>{{ usercompanie.UserCompanies_Company_id }}</td>
                                    <td class="tm-trash-icon-cell"><i class="fas fa-trash-alt tm-trash-icon"></i></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <button type="submit">Показать пользователей</button>
                        </table>

                    </div>
                    <div class="bg-white tm-block h-30">
                        <h2 class="tm-block-title d-inline-block">{{ column_right_top_name }}</h2>

                        <table class="table table-hover table-striped mt-2">
                            <tbody>
                                {% for companieshouse in companieshouse_list %}
                                <tr>
                                    <td>{{ companieshouse }}</td>
                                    <td class="tm-trash-icon-cell"><i class="fas fa-trash-alt tm-trash-icon"></i></td>
                                </tr>
                                {% endfor %}
                            </tbody>

                        </table>

                        <a href="#" class="btn btn-primary tm-table-mt">{{ column_right_bot_button }}</a>
                    </div>
                </div>
            </div>
{% endblock %}

{% block end_html %}
        </div>
    </div>
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <!-- https://jquery.com/download/ -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- https://getbootstrap.com/ -->
    <script>
        $(function () {
            $('.tm-product-name').on('click', function () {
                window.location.href = "edit-product.html";
            });
        })
    </script>

</body>
</html>
{% endblock %}